### ISSUE TITLE
Minimum Size

### ISSUE THREAD

**Issue by WWPowell-ga** [luiz-diniz/PasswordGenerator#1]
I took a quick look in Models. I see a maximum size. But shouldn't there also be a minimum size?

**Comment by luiz-diniz** [comment]
Actually the main ideia is to define a size to the password. I think it'll be more appropriate to change the name to "Password Size" or "Size" instead of maximum size or minimum.
Thanks for the advise!

**Comment by luiz-diniz** [comment]
Issue treated on commit "d5046f494a721660b531d2a7befcf3f978508a6b"
